#!/usr/bin/with-contenv bashio
set -e
export PLC_IP="$(bashio::config 'plc_ip')"
export PLC_AMS_NET_ID="$(bashio::config 'plc_ams_net_id')"
export LOCAL_AMS_NET_ID="$(bashio::config 'local_ams_net_id')"
export PLC_ADS_PORT="$(bashio::config 'plc_ads_port')"
export POLL_INTERVAL="$(bashio::config 'poll_interval')"
export LIGHT_POLL_INTERVAL="$(bashio::config 'light_poll_interval')"
export BINARY_POLL_INTERVAL="$(bashio::config 'binary_poll_interval')"
export RECONNECT_DELAY="$(bashio::config 'reconnect_delay')"
export PUBLISH_HEARTBEAT="$(bashio::config 'publish_heartbeat')"
export ADD_LOCAL_ROUTE="$(bashio::config 'add_local_route')"
export SENSORS_JSON="$(bashio::config 'sensors_json')"
export LIGHTS_JSON="$(bashio::config 'lights_json')"
export BINARY_SENSORS_JSON="$(bashio::config 'binary_sensors_json')"
export ROOMS_JSON="$(bashio::config 'rooms_json')"
export SCAN_HVAC_STATES="$(bashio::config 'scan_hvac_states')"
export SCAN_START_INDEX="$(bashio::config 'scan_start_index')"
export SCAN_END_INDEX="$(bashio::config 'scan_end_index')"
export LOG_LEVEL="$(bashio::config 'log_level')"
export MQTT_HOST="$(bashio::services mqtt 'host')"
export MQTT_PORT="$(bashio::services mqtt 'port')"
export MQTT_USERNAME="$(bashio::services mqtt 'username')"
export MQTT_PASSWORD="$(bashio::services mqtt 'password')"

bashio::log.info "Starting Beckhoff ADS Gateway v1.5.0"
bashio::log.info "PLC ${PLC_IP}, AMS ${PLC_AMS_NET_ID}, ADS port ${PLC_ADS_PORT}"
bashio::log.info "Multi-sensor mode; polling ${POLL_INTERVAL}s"
exec /opt/venv/bin/python3 /app/main.py
